apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: gedera-agents
  name: gedera-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-gedera-agents
  template:
    metadata:
      labels:
        name: pod-gedera-agents
      name: gedera-agents
    spec:
      serviceAccountName: ot-agents
      automountServiceAccountToken: true
      containers:
        - image: registry.ertis.uma.es/gedera-agents:1.0.0
          name: gedera-agents
          env:
          - name: KUBE_NAMESPACE
            value: opentwins
          - name: INSIDE_CLUSTER
            value: "True"
          ports:
            - containerPort: 8001
          imagePullPolicy: Always