apiVersion: v1
kind: ServiceAccount
metadata:
  name: ot-agents
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ot-agents-role
rules:
  - apiGroups: ["", "apps", "batch"]
    resources:
      - deployments
      - deployments/status
      - jobs
      - cronjobs
      - cronjobs/status
      - pods
      - replicasets
      - services
      - replicationcontrollers
    verbs: ["create", "get", "list", "delete", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ot-agents-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ot-agents-role
subjects:
  - kind: ServiceAccount
    name: ot-agents