apiVersion: v1
kind: Service
metadata:
  name: opentwins-agents-testing
spec:
  selector:
    name: pod-opentwins-agents-testing
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 8001
    nodePort: 30666 
    targetPort: 8001