apiVersion: v1
kind: Service
metadata:
  name: gedera-agents
spec:
  selector:
    name: pod-gedera-agents
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 8001
    nodePort: 30666 
    targetPort: 8001